# APPLICATION
spring.application.name=finance_dashboard_backend

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/finance_db
spring.datasource.username=root
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable Open Session in View (removes warning)
spring.jpa.open-in-view=false

# LOGGING (OPTIONAL)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# SWAGGER CONFIG
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true